### ISSUE TITLE
[QUESTION] Public API 

### ISSUE THREAD

**Issue by obvionaoe** [crosshare-org/crosshare#379]
Hi, do you have a public API? I'd love to try and make a native app for Android, but dont have the time to redo all the work you have already done, so an API would be really handy

Thanks

**Comment by mdirolf** [comment]
Hi! There isn't an API yet but I love the idea for an android app. I wonder if you'd be up for popping into discord sometime (linked from homepage) or chatting via email to figure out the best way forward? Cheers!
