### ISSUE TITLE
Opening constructor should prompt for puzzle setup

### ISSUE THREAD

**Issue by sarashinai** [crosshare-org/crosshare#386]
It's not immediately obvious, I had to contact albanyargus on reddit to find out, that you can change the puzzle setup by going into the more menu and choosing new puzzle. The constructor defaults to a 5x5 setup. 

I suggest that launching the constructor, when there's no puzzle being worked on, should launch the new puzzle popup.

**Comment by mdirolf** [comment]
Should be fixed on the next deploy - thanks for suggesting this!
