### ISSUE TITLE
Make auto-pause an optional feature for constructor and/or solver?

### ISSUE THREAD

**Issue by hectorpefo** [crosshare-org/crosshare#389]
Hi,

Just a frequent user who enjoys and appreciates Crosshare.

There seems to be an app feature that places a puzzle that's being solved in pause mode, with a Resume modal dialog, whenever the browser window loses focus (at least on a PC or Mac). Maybe that's not quite an accurate description, but I'm sure you know what I mean.

This is great if I'm getting interrupted from solving the puzzle by another task too urgent to let me stop the clock, and I don't want it to keep running.

But if I'm switching to another window to jot down some info from the grid relating to solving a meta puzzle, or I'm comparing the grid to a list of chemical element abbreviations, or the like, it can be inconvenient that the grid I am working on is replaced by a modal dialog every time I click away from it. 

I don't know what the best way to address that issue would be, if you think it's worth addressing, whether a user option or a constructor option or both (or even whether you have a constructor option already). But it seems like a relatively simple thing, and it's the only thing that pushes me to opt for solving with Across Lite instead, and so I thought I'd bring it up.

Thank you for Crosshare!

Hector

**Comment by mdirolf** [comment]
I think making that a user option is a good idea!

**Comment by BrianEnigma** [comment]
I'm not great at certain kinds of crossword clues and have to switch to another window to do a quick web search on a sports team/player or actor. Switching back, I have to take my hands off the keyboard and use the mouse to find that little black "resume" button. Super-annoying, and really pushes me to not want to do online crosswords anymore. This should default to the old behavior of not pausing. Or make it 100% automatic: pause and pop up that modal dialog when switching away, but automatically resume and clear out the modal dialog when returning so that no extra user action is required.

**Comment by mdirolf** [comment]
@BrianEnigma what do you think about having "press any key to resume" when you come back to the site? That might make a significant improvement for keyboard users w/o resorting to auto-resume.

**Comment by BrianEnigma** [comment]
@mdirolf That would 100% solve my particular use-case, for sure. (And probably better than an option since I can't seem to stay logged in to Google.)

**Comment by hectorpefo** [comment]
Web users who have multiple windows open just don't want the grid to
disappear when they put another window in focus.

**Comment by hectorpefo** [comment]
Yes! Thank you!
Hector

**Comment by mdirolf** [comment]
> Yes! Thank you! Hector

Yeah huge thanks to @adamthedog for tackling this one (and nailing it I think). Note that I haven't deployed yet so you won't see the new behavior until sometime this weekend when I roll it out. I will try to remember to comment here when I do.

**Comment by mdirolf** [comment]
Should be rolling out now!
