### ISSUE TITLE
Incorrectly took wrong grid as correct

### ISSUE THREAD

**Issue by davidmarchand** [crosshare-org/crosshare#393]
I was solving [this minimally Schrödinger puzzle](https://crosshare.org/es/crosswords/GYX84VnQUI948ISxrHwC/se-encuentra-muy-ajustado) (and doing somewhat poorly at it) and Crosshare gave me the win when I filled the grid, despite the fact that I got several words completely wrong.

If I fill the grid with random nonsense it correctly withholds the win, but if I reproduce my wrong play it gives me the win every time. These are the two solutions (the only difference is 74A):

![Solution1](https://user-images.githubusercontent.com/17801587/189551508-0886643a-f855-462e-9a4e-f0531dfbd013.JPG)

![Solution2](https://user-images.githubusercontent.com/17801587/189551774-8db491e3-8f0e-46e7-a603-cdc86325b034.JPG)

And this is my wrong grid (**22A** and **12D** are wrong, for example):

![WrongGrid](https://user-images.githubusercontent.com/17801587/189551537-ac83eb15-2ac5-46cc-8e5f-77c862369c25.JPG)

I seem to be able to put just about anything instead of **SEPAN** on the empty cells and it gives me the win anyway, including **XXPEN**.

**Comment by mdirolf** [comment]
Thanks for the detailed write-up! Looks like something is wrong with the solution validation code - I'll try to give it a look ASAP

**Comment by mdirolf** [comment]
I have identified the issue and fixed it in a local branch. Unfortunately I'm not sure how soon I'll be able to get a deploy out with the fix but will try ASAP. Thanks again for the report!

**Comment by davidmarchand** [comment]
No worries! It was just fun to catch and reproduce. Thanks for the quick response.
