### ISSUE TITLE
Show fill length in constructor

### ISSUE THREAD

**Issue by elle-trudgett** [crosshare-org/crosshare#423]
Useful to know how many letters are at the intersection of the cursor, like so:

![Capture-2023-03-21-120818](https://user-images.githubusercontent.com/6572020/226715542-2939dec5-3ff2-4c49-8581-0c465d4daecf.png)

Can help search up phrases in e.g. OneLook

**Comment by mdirolf** [comment]
Should go live next time there is a deploy 👍 - I might move things around at some point but for now it's located where you sketched it in.
