### ISSUE TITLE
Can't select text in clues

### ISSUE THREAD

**Issue by davidmarchand** [crosshare-org/crosshare#426]
As far as I could test, this only happens in unsolved puzzles on the web interface. Mobile puzzles don't have this issue, nor do any puzzles after being solved.

When selecting any word or part of a word in a clue that appears above the grid, the selection is reset, erased or somehow altered after a second or so. (I've been helping my mom solve 1 or 2 cryptics a week for the past few months, and she really misses the ability to select individual words or telescopic solutions in clues.)

**To reproduce:** start any unsolved puzzle on the browser, select any individual word or string of characters in the clue that appears above the grid, and wait a few seconds for the selection to disappear on its own (when the expected behavior would be for the text to remain selected indefinitely).

**Comment by mdirolf** [comment]
Good catch - thanks! 

Note to self / whoever looks at this: it looks like the clue header is re-rendering with every tick of the solve timer - we likely just need a `memo()` somewhere above the header in the virtual dom.

**Comment by mdirolf** [comment]
Should be fixed with the next deploy, hopefully by the end of the weekend :)
