### ISSUE TITLE
Feature request: scheduled publishing

### ISSUE THREAD

**Issue by elle-trudgett** [crosshare-org/crosshare#436]
Sometimes I like to create a few crosswords at a time and release one a day, but it's a bit of a hassle to do that manually/across different devices (since the crossword seems to live in local storage while I'm working on it.) It would be nice to have them saved on the server, either for manual publishing at a later date or scheduled for publishing at some time. I'd imagine this could also work well with a 'drafts' folder nicely too, for when you want to set something down and work on something else for a bit. I *believe* the only way to do this is export/import .puz right now.

**Comment by mdirolf** [comment]
You can schedule a puzzle using the "private until" feature on the clue tab. LMK if you have any questions or if that isn't doing what you need.

Follow #300 for drafts support.

**Comment by elle-trudgett** [comment]
Oh, I totally glanced over that option :) THanks!
