### ISSUE TITLE
Bug? "Starred clues" highlights any clue with bold in it (Markdown)

### ISSUE THREAD

**Issue by elle-trudgett** [crosshare-org/crosshare#437]
I noticed that when I mentioned "starred clues", it highlighted everything that I used bold (**) in. Perhaps this match could be done on just the text output of the Markdown rendering, so as to avoid picking up markdown syntax.

**Comment by mdirolf** [comment]
Good catch! Thanks :)

FYI I expect this to only be an issue when the bold occurs at the beginning or the end of the clue.

**Comment by mdirolf** [comment]
Should be fixed in the latest build.
