### ISSUE TITLE
Markdown in angle brackets not shown

### ISSUE THREAD

**Issue by Aurathic** [crosshare-org/crosshare#447]
Steps for reproduction:
- Create a crossword
- In any box in which you can enter Markdown , type some text surrounded by angle brackets, e.g. `<text>`
- Publish the crossword

Result: Any text inside of the angle brackets is not rendered.

I'm reasonably sure this isn't part of the Markdown spec -- I'm guessing it's instead a bug with how the Markdown parser / renderer attempts to escape HTML in Markdown.

**Comment by mdirolf** [comment]
I think you're right - thanks for the heads up! In the meantime you can escape one or the other angle bracket with a backslash ```\<like this>``` or ```<like this\>``` and it should work.

**Comment by mdirolf** [comment]
I think I'm going to close this as a won't-fix (at least for now). In general markdown does allow html tags (but Crosshare doesn't for security reasons). We do use angle brackets to handle links and email addresses, though. I'd like to get this working where any non-link/non-email address gets passed through as `<text>` with the angle brackets encoded, but after a brief look it seems it's going to be more trouble than it's worth to modify our markdown impl.

Thanks again for the heads up!
