### ISSUE TITLE
Send postMessage event for user starts, pauses, and completions of quizzes

### ISSUE THREAD

**Issue by elgreg** [crosshare-org/crosshare#454]
## Suggestion

When a puzzle is embedded on a page, it would be helpful if we could react to some events inside the iframe as the user is working. The specific events that come to mind are start, pause, and complete.

## Use Cases

For example, we might want to make it full-screen or lock the viewport when they start and then free the viewport when they pause or complete. Ideally, when they complete the puzzle, it would be nice to get back the amount of time it took them as part of the data object.

I'm not exactly sure what other data would be sent with the different events... maybe the current amount of time with the pause event?

**Comment by mdirolf** [comment]
This is live in staging now, should go out to prod this week. Here are the event data that embedding windows will receive (though I'm open to changing the API if something is missing or needs updating).

Completion - `didCheat` is a bit harshly named but that's what Crosshare uses internally. It will be `true` if the user used check or reveal at any point in the solve:
`{ type: "complete", elapsed: 7.205, didCheat: true }`

Pause:
`{ type: "pause", elapsed: 7.205 }`

Start/resume:
`{ type: "resume" }`

Also note that it is likely / expected that you might receive multiple identical completion events - you should listen for the first one and then consider the puzzle done from that point on.
