### ISSUE TITLE
Allow specifying custom font in embed

### ISSUE THREAD

**Issue by elgreg** [crosshare-org/crosshare#455]
## Suggestion

Our site uses some fancy fonts. It would be great if we could specify the URL for a font file to be loaded in the embed and then the name of it that would end up in the stylesheet. The font would need an Access-Control-Allow-Origin that permits crosshare.org.

**Comment by mdirolf** [comment]
@elgreg any reason why you'd need to be able to specify the name of it? Right now crosshare only uses a single font for the entire site so I'm thinking I'd just prepend something like "CrosshareCustom" to the front of that list in our main stylesheet. Then in the general case nothing changes. But if an embedder has specified a URL for a custom font we add a `@font-face` declaration that names the font CrosshareCustom.

Does that make sense? I guess I can't see any reason the embedder would need to know what the font ends up getting called. Plus this way I can envision easily adding some more font names (CrosshareClues or CrosshareGrid or something) if and when it seems necessary.

**Comment by elgreg** [comment]
Good point! That would work and means less chance of CSS injection (not to mention typos).

**Comment by mdirolf** [comment]
This is mostly complete - going to try to get it pushed and live in the next few days.
