### ISSUE TITLE
User setting for displaying exact meta completion times

### ISSUE THREAD

**Issue by benchen71** [crosshare-org/crosshare#460]
I need to be able to copy and paste the solver list with the exact meta completion times, so that I can then work out where to insert the names of solvers who direct message me with their meta answer. The new "X days ago" format is not specific enough, and I don't really want to have to mouse over lots of entries in order to find the right place!

Would it be possible to add a user setting that turns on the old completion time format?

**Comment by mdirolf** [comment]
There are completion times in ISO format on the stats page, both in the table and downloadable as a CSV - do those options not work for you?

I definitely don't want to add a setting for this, but would like to figure out something that works for you!

**Comment by benchen71** [comment]
Yes, the stats page should work fine. I'll just have to adjust my workflow!

**Comment by mdirolf** [comment]
Great! LMK if there's anything we can add to the stats page to help out.
