### ISSUE TITLE
Can't scroll down on notifications list

### ISSUE THREAD

**Issue by revuluri** [crosshare-org/crosshare#469]
Using Crosshare in Chrome on a macOS laptop, when I have a lot of notifications, I can't scroll down the list to see the later ones if the window itself is not scrollable — like on the page of a puzzle. (When the main window is "tall" like the homepage, I can scroll the whole window down so it does not block me from seeing them.)

**Comment by mdirolf** [comment]
Thank you for the heads up! This should be fixed by the above commit the next time we deploy (hopefully w/in the next day or two).
