### ISSUE TITLE
Distinguish types of notifications

### ISSUE THREAD

**Issue by revuluri** [crosshare-org/crosshare#470]
As a solver, commenter, and occasional constructor who periodically tries to step away from the site, when I have a lot of notifications I would like to be able to quickly distinguish which are new puzzles, which are replies to my comments, and which are comments on my puzzles. (I imagine this could be done by sorting by type, coloring the different kinds different colors, adding an emoji as an icon, or some other way.)

**Comment by mdirolf** [comment]
Love this idea - thanks! Added in the above commit, should be visible on the next deploy.

**Comment by revuluri** [comment]
Thanks @mdirolf!

I should have had this idea earlier, and maybe it is not worthwhile, but: what about distinguishing (or sorting) "new puzzle" notifications by size and/or difficulty (and/or average solve time)? The shortest "snacks" (e.g., easy minis) would be first (or marked as fast) and then the other ones would be later on.
