### ISSUE TITLE
Multicell cut and paste feature

### ISSUE THREAD

**Issue by legnes** [crosshare-org/crosshare#476]
During construction, it might be nice to have the ability to cut an entire answer and paste it into a different set of cells. This could be useful when shuffling around theme/core answers to set up the scaffold of the grid. Currently it seems like there is no copy/cut, and paste only pastes as a rebus.

The specific sub-features/behaviors might be something like:
1. **Cut (or copy, or both?) multiple cells.** There are a lot of ways this could work, and I'd be curious what other people think! One simple option would be to cut from the current cell in the current direction until you hit a block square, bar, or the end of the grid.
2. **Paste multiple cells.** Attempts to spread the pasted word across multiple cells, starting at the current cell and proceeding in the current direction until hitting a block square or bar.
3. **Cut single cell.** Just for parity

**Comment by mdirolf** [comment]
I love the idea. One option (although it would be more complicated) would be to build an interface for selecting arbitrary sections/subsets of the grid. This would be useful for some other issues too, like #140. This could potentially be limited to rectangular selections which would make dragging out selections easier and probably make pasting easier as well.
