### ISSUE TITLE
Linked Clue Popups Hidden Under Keyboard

### ISSUE THREAD

**Issue by schmidzy** [crosshare-org/crosshare#477]
![Screenshot_20240328-202435](https://github.com/crosshare-org/crosshare/assets/165351060/57fbb845-7348-42a8-97a1-7781e5e0a931)

See screenshot — keyboard is covering up linked clue popups. Noticed only recently. This is on Chrome for Android 13.

**Comment by mdirolf** [comment]
It appears like this broke in March '23 - thanks for being the first to bother reporting it! I've pushed a change that should fix the position of the tooltip so it's directly beneath the reference now. It might still require a scroll depending on the location of the reference but I think the behavior is "correct" now. LMK if you notice anything amiss!

**Comment by mdirolf** [comment]
Let's get this above the keyboard, too. Reopening and hoping to fix along with #479

**Comment by mdirolf** [comment]
Fixed
