### ISSUE TITLE
Add some more publish warnings

### ISSUE THREAD

**Issue by mdirolf** [crosshare-org/crosshare#495]
This can be broken out into separate issues if needed (or tackled one at a time!) but just listing here since I've thought of a few:

- [ ] Unches when no "cryptic" tag is present (use `hasUnches` in `gridBase.ts`)
- [ ] Two-letter words

These two are a bit more complex:
- [ ] A clue has something that looks like a reference (e.g. 39-Across) but there is no matching entry
- [ ] Clues all end in enumerations (e.g. `(4)` or `(2, 3)` or `(5, two words)`) but one is missing
- [ ] Clues all end in enumerations but one (or more) doesn't match the length of the entry

**Comment by legnes** [comment]
Another thing that came up when discussing enumerations was adding a button to append them to all clues, and possibly also a button to undo or remove them. Possibly that should be its own issue/feature, but mentioning it here just to make sure it's written down!
