### ISSUE TITLE
Button to append enumeration to all clues

### ISSUE THREAD

**Issue by mdirolf** [crosshare-org/crosshare#498]
Another thing that came up when discussing enumerations was adding a button to append them to all clues, and possibly also a button to undo or remove them. Possibly that should be its own issue/feature, but mentioning it here just to make sure it's written down!

_Originally posted by @legnes in https://github.com/crosshare-org/crosshare/issues/495#issuecomment-2075905710_

Thanks for remembering to track that @legnes! I do think we should make sure to somehow support undo for this just as it chnages every clue and would be a lot of work for the constructor to manually undo.

One option would be to add clue text changes to the history state. I pointed out in Discord that this could get weird if you were undoing clue changes on the grid page w/o realizing it or vice versa. But if we also added mode changes btwn grid+clue view to the history state maybe that is the simplest solution.

**Comment by legnes** [comment]
As another possibility: do you think it would work to put enumerations in a custom markdown directive? Might make it easier to detect them (for warnings), and to remove them (instead of undoing) if you decide you don't want them?

**Comment by mdirolf** [comment]
Something like that is an option but since so many folks use enumerations in the (x) syntax I think my preference is to try to support them without making folks learn a new syntax

**Comment by legnes** [comment]
Re: clue text undo, my two cents is that I feel like it'd be confusing:
- Having grid/clue mode on the stack is certainly a little odd.
- The text inputs themselves already support undo natively, and any attempt to override that would probably be a little worse
- Would ctrl+z work from "anywhere" in the clue mode page? (That is, regardless of focus state). I don't think the UI makes it very clear.

What about a "remove enumerations" button? To me it seems more flexible than undo in that you could add enums, edit some clues, and then remove the enums without losing your edits. The downside is that it'd rely on being able to identify enumerations, which is definitely imprecise. This is where a custom markdown directive could be helpful. But I think/hope the current detection is good enough to suffice?

What do you think @mdirolf? Is the auto-enum-detection too brittle to rely on for this?

**Comment by mdirolf** [comment]
@legnes you've convinced me about the clue text undo stuff!

I think the auto-enum-detection is probably good enough but I honestly can't imagine a "remove enumerations" button being generally useful - it'd likely only get used in this case where somebody hits the Add button not realizing what it does and then wants to undo it. So I kinda feel like it'd be mostly UI clutter and then the feature would only be 95% correct (if it removes any false positives)

I know this is a bit complicated but what about a time-limited undo link in a snackbar that shows up after adding enumerations? Basically exactly what gmail does for a sent message: 
![image](https://github.com/crosshare-org/crosshare/assets/3546/d0c77b0e-f46b-4d94-801a-be8ac0ae4d8f)

I think that's my preferred solution at the moment but another option would be to add a modal gate before actually adding the enumerations where we could explain what enumerations are, etc. "Are you sure you want to do this?".

**Comment by legnes** [comment]
I like both of those options a lot!
